version: '3'

services:

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server

  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      - server
